version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build: ./newchecks-backend
    ports:
      - "5004:5004"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
