#!/bin/bash
echo "🖥️  NewChecks Dedicated Server Setup Guide"
echo "==========================================="
echo ""
echo "1. Get a cheap computer for the office:"
echo "   - Old desktop computer ($50-100)"
echo "   - Mac Mini (used ~$200-300)"
echo "   - Intel NUC (~$300-400)"
echo "   - Raspberry Pi 4 (~$100-150)"
echo ""
echo "2. Install the app on that computer"
echo "3. Leave it running 24/7 at the office"
echo "4. Everyone accesses via the same network IP"
echo ""
echo "Benefits:"
echo "✅ Completely local (no internet access)"
echo "✅ Always available when you're away"
echo "✅ Your main computer stays free"
echo "✅ Low power consumption"
echo "✅ Maximum security"
